<script setup lang="ts">
import{onMounted,ref,watch}from'vue';import{MediaRecorderAdapter}from'../adapters/media-recorder.adapter';import{WebAudioAnalyzerAdapter}from'../adapters/web-audio-analyzer.adapter';import{WebAudioCropperAdapter}from'../adapters/web-audio-cropper.adapter';import{WebAudioMixerAdapter}from'../adapters/web-audio-mixer.adapter';import{CanvasCoverRendererAdapter}from'../adapters/canvas-cover-renderer.adapter';import{IndexedDbMemeRepository}from'../adapters/indexeddb-meme.repository';import{BrowserShareAdapter}from'../adapters/browser-share.adapter';import{useStudio,type StudioDependencies}from'./useStudio';import RecorderPanel from'./components/RecorderPanel.vue';import CropTimeline from'./components/CropTimeline.vue';import MixWorkbench from'./components/MixWorkbench.vue';import EmotionPanel from'./components/EmotionPanel.vue';import CoverWorkshop from'./components/CoverWorkshop.vue';import MemeGallery from'./components/MemeGallery.vue';import SharePanel from'./components/SharePanel.vue';
const props=defineProps<{dependencies?:StudioDependencies}>();const defaults:StudioDependencies={recorder:new MediaRecorderAdapter(),analyzer:new WebAudioAnalyzerAdapter(),cropper:new WebAudioCropperAdapter(),mixer:new WebAudioMixerAdapter(),renderer:new CanvasCoverRendererAdapter(),repository:new IndexedDbMemeRepository(),share:new BrowserShareAdapter()};const studio=useStudio(props.dependencies??defaults);const recording=ref(false);async function start(){await studio.startRecording();recording.value=!studio.error.value}async function stop(){await studio.stopRecording();recording.value=false}onMounted(()=>studio.loadCollection());
const stages=['录音','裁剪','混音','情绪','封面','作品集'] as const;
const stageKeys=['record','crop','mix','emotion','cover','collection'] as const;
// 试听地址只跟随“确认后的混音”，参数变化即失效，不会听到旧结果
const mixUrl=ref('');let mixObjectUrl='';
const createObjectUrl=typeof URL!=='undefined'&&URL.createObjectURL?URL.createObjectURL.bind(URL):(b:Blob)=>`blob:${b.size}-${Date.now()}`;
const revokeObjectUrl=typeof URL!=='undefined'&&URL.revokeObjectURL?URL.revokeObjectURL.bind(URL):()=>{};
watch(studio.confirmedMix,(blob)=>{if(mixObjectUrl)revokeObjectUrl(mixObjectUrl);mixObjectUrl=blob?createObjectUrl(blob):'';mixUrl.value=mixObjectUrl;});
const canPreviewMix=()=>!!studio.voiceSource.value;
</script>
<template><div class="sound-app"><header><div class="logo">声<span>!</span></div><div><small>SOUND REACTION STUDIO / 005</small><h1>声音表情包工坊</h1></div><nav><button v-for="(s,i) in stages" :key="s" :class="{active:stageKeys[i]===studio.stage.value}">{{ i+1 }} {{ s }}</button></nav></header><main><section class="intro"><div><span class="kicker">MAKE SOME NOISE. MAKE IT YOURS.</span><h2>让声音，<em>长出表情。</em></h2><p>录一句、混入背景、认情绪、做封面。十秒就能生成一张会发声的表情包。</p></div><div class="intro-badge"><b>10</b><span>SECONDS<br>OF ATTITUDE</span></div></section><div v-if="studio.error.value" class="error-banner">{{studio.error.value}}</div><div v-if="studio.notice.value" class="notice-banner">{{studio.notice.value}}</div><RecorderPanel v-if="studio.stage.value==='record'" :recording="recording" :level="studio.level.value" @record="start" @stop="stop" @import="studio.importAudio"/><CropTimeline v-else-if="studio.stage.value==='crop'" :duration="studio.draft.duration" :start="studio.draft.cropStart" :end="studio.draft.cropEnd" @update-start="studio.draft.cropStart=$event" @update-end="studio.draft.cropEnd=$event" @analyze="studio.enterMix"/><MixWorkbench v-else-if="studio.stage.value==='mix'&&canPreviewMix()" :voice-duration="studio.draft.duration" :background-name="studio.backgroundName.value" :background-duration="studio.backgroundDuration.value" :settings="studio.mixSettings" :confirmed="!!studio.confirmedMix.value" :dirty="studio.mixDirty.value" :clip-risk="studio.clipRisk.value" :peak="studio.pendingPeak.value" :previewing="studio.previewing.value" :audio-url="mixUrl" @import-background="studio.importBackground" @remove-background="studio.removeBackground" @patch="studio.patchSettings" @preview="studio.previewMix" @confirm="studio.confirmMix" @revert="studio.revertMix" @analyze="studio.analyze" @back="studio.stage.value='crop'"/><EmotionPanel v-else-if="studio.stage.value==='emotion'&&studio.emotion.value" :result="studio.emotion.value" @select="studio.selectEmotion" @next="studio.goCover"/><CoverWorkshop v-else-if="studio.stage.value==='cover'" :config="studio.cover.value" :title="studio.draft.title" @patch="studio.cover.value={...studio.cover.value,...$event}" @title="studio.draft.title=$event" @save="studio.save()"/><MemeGallery v-else :items="studio.collection.value" @edit="studio.editMeme" @remove="studio.deleteMeme" @share="studio.shareMeme" @new="studio.newRecording"/><SharePanel/></main></div></template>
